filegroup(
    name = "config",
    srcs = ["config.h"],
    visibility = ["//visibility:public"],
    )   
filegroup(
    name = "config_m4",
    srcs = ["config.m4"],
    visibility = ["//visibility:public"],
    )   
